# Generated by Django 4.0.3 on 2022-03-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_delete_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='contactus',
        ),
    ]
